name: v*.*.* -PR-> master

on:
  push:
    branches: [ v*.*.* ]

jobs:
  auto-pr:
    name: Automated Master Branch PR
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    steps:
          - name: Extract branch name on pull request
            shell: bash
            run: |
              echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          - name: Print debug data before publishing
            run: |
              echo "Source branch: ${{ env.SOURCE_BRANCH }}"
              echo "   Event name: ${{ github.event_name }}"
              echo "  Repo. name: ${{ github.event.repository.name }}"
          # Work around https://github.com/actions/checkout/issues/760
          - name: Add safe.directory
            run: |
              git config --global --add safe.directory /usr/lib/flutter
              git config --global --add safe.directory /github/workspace
              git config --global --add safe.directory $PWD
          # ref.: https://github.com/actions/checkout, v3.0.0
          - name: Checkout repository
            uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
          - name: Create PR from a version branch to master after version branch push
            # ref. repo-sync/pull-request is broken, using cea2aj/pull-request instead
            uses: cea2aj/pull-request@84eb0c3478f13651e5649367941b867ca02d7926
            if: startsWith(env.SOURCE_BRANCH, 'v') && contains(env.SOURCE_BRANCH, '.')
            with:
              github_token: ${{ secrets.REPO_ACCESS }}
              source_branch: ${{ env.SOURCE_BRANCH }}
              destination_branch: 'master'
              pr_title: "${{ env.SOURCE_BRANCH }} -> master" 
              pr_label: "kira-automation"
              pr_assignee: "asmodat"
              pr_allow_empty: true
          - name: Create PR from a version branch to dev after version branch push
            # ref. repo-sync/pull-request is broken, using cea2aj/pull-request instead
            uses: cea2aj/pull-request@84eb0c3478f13651e5649367941b867ca02d7926
            if: startsWith(env.SOURCE_BRANCH, 'v') && contains(env.SOURCE_BRANCH, '.')
            with:
              github_token: ${{ secrets.REPO_ACCESS }}
              source_branch: ${{ env.SOURCE_BRANCH }}
              destination_branch: 'dev'
              pr_title: "${{ env.SOURCE_BRANCH }} -> dev" 
              pr_label: "kira-automation"
              pr_assignee: "AmanuelYosief"
              pr_allow_empty: true